### ISSUE TITLE
여보! AWS 댁에 개발 DB 놓아 드려야겠어요

### ISSUE THREAD

**Issue by pySatellite** [beyond-sw-camp/beyond-sw-camp-be01_last-dance#81]
- [x] aws ec2 접속
- [x] aws RDS 염탐 -> 어떤 버전을 사용하나?
- [x] ec2 docker 설치
- [x] 도커허브에서 디비 설치
```
$ docker run --detach --name some-mariadb --env MARIADB_USER=example-user --env MARIADB_PASSWORD=my_cool_secret --env MARIADB_DATABASE=exmple-database --env MARIADB_ROOT_PASSWORD=my-secret-pw  mariadb:latest
```
- [x] 방화벽 열기 - 접속확인

![image](https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/assets/87309910/f96ed276-c05a-4d59-aeac-9aed60a27505)
- [출처 여보! 아버님 댁에 보일러 놓아 드려야겠어요](https://namu.wiki/w/%EC%97%AC%EB%B3%B4!%20%EC%95%84%EB%B2%84%EB%8B%98%20%EB%8C%81%EC%97%90%20%EB%B3%B4%EC%9D%BC%EB%9F%AC%20%EB%86%93%EC%95%84%20%EB%93%9C%EB%A0%A4%EC%95%BC%EA%B2%A0%EC%96%B4%EC%9A%94.)

**Comment by pySatellite** [comment]
### 활용
- docker-compose.yml
```
name: restdb
services:
  proxy:
    image: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "8888:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - rest
  
  rest:
    build: .
    ports:
      - 7777:8080
    platform: linux/amd64
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:10.5.24-focal
    ports: 
      - 33306:3306
    volumes:
        - ./mariadb/conf.d:/etc/mysql/conf.d
        - ./mariadb/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: my_root_password
      MARIADB_USER: my_user
      MARIADB_PASSWORD: my_password
      MARIADB_DATABASE: my_database
```

- application.properties
```
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://db:3306/my_database
spring.datasource.username=my_user
spring.datasource.password=my_password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
```
